version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    -run:
        name: sdk manager accept
        command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses

    - run:
    name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
    command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  - run:
        name: Assemble APKs
        command: ./gradlew assembleAndroidTest assemble
  - run:
        name: Dump Google Cloud Credentials to file
        command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
  - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
  - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
  - run:
        name: Configure environment
        command: |
            echo 'export APK_PATH=`find . -path "*.apk" ! -path "*unaligned.apk" ! -path "*Test*.apk" -print -quit`' >> $BASH_ENV
            echo 'export TEST_APK_PATH=`find "." "-path" "*Test*.apk" -print -quit`' >> $BASH_ENV
 - run:
        name: Run UI Tests
        command: gcloud firebase test android run --type instrumentation --app ${APK_PATH} --test ${TEST_APK_PATH} --device model=Nexus6P,version=27,locale=en,orientation=portrait --timeout 30m
        no_output_timeout: 30m